from __future__ import annotations

import argparse
import datetime as _dt
import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Route:
    path: str
    methods: tuple[str, ...]
    source: str


_LAST_UPDATED_START = "<!-- AUTOGENERATED:LAST_UPDATED -->"
_LAST_UPDATED_END = "<!-- /AUTOGENERATED:LAST_UPDATED -->"
_GENERATED_FROM_START = "<!-- AUTOGENERATED:GENERATED_FROM_COMMIT -->"
_GENERATED_FROM_END = "<!-- /AUTOGENERATED:GENERATED_FROM_COMMIT -->"

_ROUTES_START = "<!-- AUTOGENERATED:START api_routes -->"
_ROUTES_END = "<!-- AUTOGENERATED:END api_routes -->"
_DATA_SCHEMAS_START = "<!-- AUTOGENERATED:START data_schemas -->"
_DATA_SCHEMAS_END = "<!-- AUTOGENERATED:END data_schemas -->"
_CRITICAL_ENV_START = "<!-- AUTOGENERATED:START critical_env -->"
_CRITICAL_ENV_END = "<!-- AUTOGENERATED:END critical_env -->"


def _repo_root() -> Path:
    # tools/ -> repo root
    return Path(__file__).resolve().parent.parent


def _agent_markdown_files(repo_root: Path) -> list[Path]:
    agent_dir = repo_root / ".agent"
    if not agent_dir.exists():
        return []
    return sorted([p for p in agent_dir.glob("*.md") if p.is_file()])


def _extract_routes(repo_root: Path) -> list[Route]:
    routes_dir = repo_root / "backend" / "routes"
    if not routes_dir.exists():
        return []

    route_decorator = re.compile(
        r"""@bp\.route\(\s*(['"])(?P<path>.+?)\1(?P<rest>[^)]*)\)""",
        re.VERBOSE,
    )
    methods_re = re.compile(r"""methods\s*=\s*\[(?P<methods>[^\]]*)\]""")
    method_token_re = re.compile(r"""['"](?P<m>[A-Z]+)['"]""")

    routes: list[Route] = []
    for py in sorted(routes_dir.glob("*.py")):
        rel = py.relative_to(repo_root).as_posix()
        try:
            text = py.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            text = py.read_text(encoding="utf-8", errors="replace")

        for m in route_decorator.finditer(text):
            path = m.group("path").strip()
            rest = m.group("rest") or ""
            methods_match = methods_re.search(rest)
            if methods_match:
                tokens = method_token_re.findall(methods_match.group("methods"))
                methods = tuple(dict.fromkeys(t.strip().upper() for t in tokens if t.strip()))
            else:
                methods = ("GET",)

            routes.append(Route(path=path, methods=methods or ("GET",), source=rel))

    # Normalize: prefer stable ordering
    routes.sort(key=lambda r: (r.path, ",".join(r.methods), r.source))
    return routes


def _render_routes_markdown(routes: list[Route]) -> str:
    if not routes:
        return "_Routes не найдены (папка backend/routes отсутствует или пуста)._"

    lines: list[str] = []
    lines.append("")
    lines.append("Таблица: **Методы | Путь | Источник**")
    lines.append("")
    lines.append("| Методы | Путь | Источник |")
    lines.append("|---|---|---|")

    for r in routes:
        methods = ",".join(r.methods)
        lines.append(f"| `{methods}` | `{r.path}` | `{r.source}` |")

    lines.append("")
    lines.append(f"Итого: **{len(routes)}** route‑декораторов `@bp.route(...)`.")
    return "\n".join(lines).lstrip("\n")


def _current_commit(repo_root: Path) -> str:
    try:
        return (
            subprocess.check_output(
                ["git", "rev-parse", "HEAD"],
                cwd=repo_root,
                stderr=subprocess.DEVNULL,
                text=True,
            )
            .strip()
        )
    except Exception:
        return "unknown"


def _shorten_list(values: list[str], limit: int = 10) -> str:
    if len(values) <= limit:
        return ", ".join(f"`{v}`" for v in values) if values else "-"
    shown = ", ".join(f"`{v}`" for v in values[:limit])
    return f"{shown}, ... (+{len(values) - limit})"


def _render_data_schemas_markdown(repo_root: Path) -> str:
    data_dir = repo_root / "data"
    files = sorted(data_dir.glob("*.json"))
    if not files:
        return "_JSON-файлы в `data/` не найдены._"

    lines: list[str] = []
    lines.append("Таблица: **Файл | Top-level тип | Записей | Ключи/поля (срез)**")
    lines.append("")
    lines.append("| Файл | Top-level тип | Записей | Ключи/поля (срез) |")
    lines.append("|---|---|---:|---|")

    for path in files:
        rel = path.relative_to(repo_root).as_posix()
        try:
            raw = path.read_text(encoding="utf-8")
            if not raw.strip():
                lines.append(f"| `{rel}` | `empty_file` | 0 | - |")
                continue
            payload = json.loads(raw)
        except Exception:
            lines.append(f"| `{rel}` | `invalid_json` | - | Не удалось распарсить |")
            continue

        if isinstance(payload, list):
            record_count = len(payload)
            if payload and isinstance(payload[0], dict):
                keys = sorted(str(k) for k in payload[0].keys())
                key_slice = _shorten_list(keys)
                top_type = "array<object>"
            elif payload:
                top_type = f"array<{type(payload[0]).__name__}>"
                key_slice = "-"
            else:
                top_type = "array<empty>"
                key_slice = "-"
        elif isinstance(payload, dict):
            record_count = len(payload)
            top_keys = sorted(str(k) for k in payload.keys())
            top_type = "object"
            key_slice = _shorten_list(top_keys)
        else:
            record_count = 1
            top_type = type(payload).__name__
            key_slice = "-"

        lines.append(f"| `{rel}` | `{top_type}` | {record_count} | {key_slice} |")

    return "\n".join(lines)


def _extract_backend_env_vars(repo_root: Path) -> list[str]:
    backend = repo_root / "backend"
    names: set[str] = set()
    env_re = re.compile(r"""os\.getenv\(\s*['"]([A-Z0-9_]+)['"]""")
    for py in sorted(backend.rglob("*.py")):
        try:
            text = py.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            text = py.read_text(encoding="utf-8", errors="replace")
        for name in env_re.findall(text):
            names.add(name)
    return sorted(names)


def _extract_frontend_env_vars(repo_root: Path) -> list[str]:
    frontend = repo_root / "frontend" / "src"
    names: set[str] = set()
    react_env_re = re.compile(r"""REACT_APP_[A-Z0-9_]+""")
    for js in sorted(frontend.rglob("*.*")):
        if js.suffix not in {".js", ".jsx", ".ts", ".tsx"}:
            continue
        try:
            text = js.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            text = js.read_text(encoding="utf-8", errors="replace")
        for name in react_env_re.findall(text):
            names.add(name)
    return sorted(names)


def _is_sensitive_env_var(name: str) -> bool:
    sensitive_tokens = ("SECRET", "TOKEN", "PASSWORD", "DSN", "CHAT_ID", "KEY")
    return any(token in name for token in sensitive_tokens)


def _render_critical_env_markdown(repo_root: Path) -> str:
    backend_vars = _extract_backend_env_vars(repo_root)
    frontend_vars = _extract_frontend_env_vars(repo_root)
    backend_sensitive = [v for v in backend_vars if _is_sensitive_env_var(v)]
    backend_control = [v for v in backend_vars if "DEPLOY" in v or "SABOR_DB_PATH" in v or "DB_PATH" in v]

    lines: list[str] = []
    lines.append("### Backend (env)")
    lines.append(f"- Всего обнаружено: **{len(backend_vars)}**")
    lines.append(f"- Чувствительные: {_shorten_list(backend_sensitive, limit=20)}")
    lines.append(f"- Критичные для управления/деплоя: {_shorten_list(sorted(set(backend_control)), limit=20)}")
    lines.append("")
    lines.append("### Frontend (`REACT_APP_*`)")
    lines.append(f"- Всего обнаружено: **{len(frontend_vars)}**")
    lines.append(f"- Используемые переменные: {_shorten_list(frontend_vars, limit=20)}")
    lines.append("")
    lines.append("> Примечание: `REACT_APP_*` публичны после сборки фронтенда; секреты туда не помещать.")
    return "\n".join(lines)


def _replace_block(text: str, start: str, end: str, replacement: str) -> str:
    if start not in text or end not in text:
        raise SystemExit(f"Markers not found: {start} ... {end}")

    before, rest = text.split(start, 1)
    _, after = rest.split(end, 1)

    if not replacement.endswith("\n"):
        replacement += "\n"

    return before + start + "\n" + replacement + end + after


def _replace_inline(text: str, start: str, end: str, replacement: str) -> str:
    if start not in text or end not in text:
        raise SystemExit(f"Markers not found: {start} ... {end}")

    before, rest = text.split(start, 1)
    _, after = rest.split(end, 1)
    return before + start + replacement + end + after


def main() -> int:
    parser = argparse.ArgumentParser(description="Update .agent/knowledge.md autogenerated sections")
    parser.add_argument("--check", action="store_true", help="Exit with non-zero if changes are needed")
    args = parser.parse_args()

    repo_root = _repo_root()
    agent_files = _agent_markdown_files(repo_root)
    if not agent_files:
        raise SystemExit(f"No markdown files found in: {repo_root / '.agent'}")

    today = _dt.date.today().isoformat()
    commit = _current_commit(repo_root)
    routes_md = _render_routes_markdown(_extract_routes(repo_root))
    data_schemas_md = _render_data_schemas_markdown(repo_root)
    critical_env_md = _render_critical_env_markdown(repo_root)

    changed: list[Path] = []
    for path in agent_files:
        original = path.read_text(encoding="utf-8")
        updated = original

        if _LAST_UPDATED_START in updated and _LAST_UPDATED_END in updated:
            updated = _replace_inline(updated, _LAST_UPDATED_START, _LAST_UPDATED_END, today)

        if _GENERATED_FROM_START in updated and _GENERATED_FROM_END in updated:
            updated = _replace_inline(updated, _GENERATED_FROM_START, _GENERATED_FROM_END, commit)

        if _ROUTES_START in updated and _ROUTES_END in updated:
            updated = _replace_block(updated, _ROUTES_START, _ROUTES_END, routes_md)

        if _DATA_SCHEMAS_START in updated and _DATA_SCHEMAS_END in updated:
            updated = _replace_block(updated, _DATA_SCHEMAS_START, _DATA_SCHEMAS_END, data_schemas_md)

        if _CRITICAL_ENV_START in updated and _CRITICAL_ENV_END in updated:
            updated = _replace_block(updated, _CRITICAL_ENV_START, _CRITICAL_ENV_END, critical_env_md)

        if updated != original:
            changed.append(path)
            if not args.check:
                path.write_text(updated, encoding="utf-8")

    if args.check:
        return 2 if changed else 0

    if changed:
        for p in changed:
            print(f"Updated: {p}")
    else:
        print("No changes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
