from __future__ import annotations

import argparse
import datetime as _dt
import re
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Route:
    path: str
    methods: tuple[str, ...]
    source: str


_LAST_UPDATED_START = "<!-- AUTOGENERATED:LAST_UPDATED -->"
_LAST_UPDATED_END = "<!-- /AUTOGENERATED:LAST_UPDATED -->"

_ROUTES_START = "<!-- AUTOGENERATED:START api_routes -->"
_ROUTES_END = "<!-- AUTOGENERATED:END api_routes -->"


def _repo_root() -> Path:
    # tools/ -> repo root
    return Path(__file__).resolve().parent.parent


def _agent_markdown_files(repo_root: Path) -> list[Path]:
    agent_dir = repo_root / ".agent"
    if not agent_dir.exists():
        return []
    return sorted([p for p in agent_dir.glob("*.md") if p.is_file()])


def _extract_routes(repo_root: Path) -> list[Route]:
    routes_dir = repo_root / "backend" / "routes"
    if not routes_dir.exists():
        return []

    route_decorator = re.compile(
        r"""@bp\.route\(\s*(['"])(?P<path>.+?)\1(?P<rest>[^)]*)\)""",
        re.VERBOSE,
    )
    methods_re = re.compile(r"""methods\s*=\s*\[(?P<methods>[^\]]*)\]""")
    method_token_re = re.compile(r"""['"](?P<m>[A-Z]+)['"]""")

    routes: list[Route] = []
    for py in sorted(routes_dir.glob("*.py")):
        rel = py.relative_to(repo_root).as_posix()
        try:
            text = py.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            text = py.read_text(encoding="utf-8", errors="replace")

        for m in route_decorator.finditer(text):
            path = m.group("path").strip()
            rest = m.group("rest") or ""
            methods_match = methods_re.search(rest)
            if methods_match:
                tokens = method_token_re.findall(methods_match.group("methods"))
                methods = tuple(dict.fromkeys(t.strip().upper() for t in tokens if t.strip()))
            else:
                methods = ("GET",)

            routes.append(Route(path=path, methods=methods or ("GET",), source=rel))

    # Normalize: prefer stable ordering
    routes.sort(key=lambda r: (r.path, ",".join(r.methods), r.source))
    return routes


def _render_routes_markdown(routes: list[Route]) -> str:
    if not routes:
        return "_Routes не найдены (папка backend/routes отсутствует или пуста)._"

    lines: list[str] = []
    lines.append("")
    lines.append("Таблица: **Методы | Путь | Источник**")
    lines.append("")
    lines.append("| Методы | Путь | Источник |")
    lines.append("|---|---|---|")

    for r in routes:
        methods = ",".join(r.methods)
        lines.append(f"| `{methods}` | `{r.path}` | `{r.source}` |")

    lines.append("")
    lines.append(f"Итого: **{len(routes)}** route‑декораторов `@bp.route(...)`.")
    return "\n".join(lines).lstrip("\n")


def _replace_block(text: str, start: str, end: str, replacement: str) -> str:
    if start not in text or end not in text:
        raise SystemExit(f"Markers not found: {start} ... {end}")

    before, rest = text.split(start, 1)
    _, after = rest.split(end, 1)

    if not replacement.endswith("\n"):
        replacement += "\n"

    return before + start + "\n" + replacement + end + after


def _replace_inline(text: str, start: str, end: str, replacement: str) -> str:
    if start not in text or end not in text:
        raise SystemExit(f"Markers not found: {start} ... {end}")

    before, rest = text.split(start, 1)
    _, after = rest.split(end, 1)
    return before + start + replacement + end + after


def main() -> int:
    parser = argparse.ArgumentParser(description="Update .agent/knowledge.md autogenerated sections")
    parser.add_argument("--check", action="store_true", help="Exit with non-zero if changes are needed")
    args = parser.parse_args()

    repo_root = _repo_root()
    agent_files = _agent_markdown_files(repo_root)
    if not agent_files:
        raise SystemExit(f"No markdown files found in: {repo_root / '.agent'}")

    today = _dt.date.today().isoformat()
    routes_md = _render_routes_markdown(_extract_routes(repo_root))

    changed: list[Path] = []
    for path in agent_files:
        original = path.read_text(encoding="utf-8")
        updated = original

        if _LAST_UPDATED_START in updated and _LAST_UPDATED_END in updated:
            updated = _replace_inline(updated, _LAST_UPDATED_START, _LAST_UPDATED_END, today)

        if _ROUTES_START in updated and _ROUTES_END in updated:
            updated = _replace_block(updated, _ROUTES_START, _ROUTES_END, routes_md)

        if updated != original:
            changed.append(path)
            if not args.check:
                path.write_text(updated, encoding="utf-8")

    if args.check:
        return 2 if changed else 0

    if changed:
        for p in changed:
            print(f"Updated: {p}")
    else:
        print("No changes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
